name: VoicePolyglot
options:
  bundleIdPrefix: com.dubravcik
  deploymentTarget:
    iOS: "15.0"
targets:
  VoicePolyglot:
    type: application
    platform: iOS
    sources:
      - Sources
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dubravcik.VoicePolyglot
        DEVELOPMENT_TEAM: "" # fill in your Apple Developer team ID
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
